steps:
- powershell: azure-pipelines/Set-MSBuildPath.ps1

- script: echo $PATH
  displayName: Print PATH

- script: dep/winpty/vcbuild.bat --msvc-platform x64 --toolset v142 --gyp-msvs-version 2017
  displayName: Build x64 WinPty
